### ISSUE TITLE
Vaadin-text-field might have multiple definitions

### ISSUE THREAD

**Issue by hari2m** [vaadin/vaadin-text-field#451]
I just imported the new 2.6.0-alpha3 version and the module does not build. Vaadin-text-field fails to build due to below message.

Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': the name "vaadin-text-field" has already been used with this registry
    at Module../node_modules/@vaadin/vaadin-text-field/src/vaadin-text-field.js (http://localhost:3000/vendors~BrokerOffer-brokerOffer~BrokerOffer-brokerOfferTemplate~Home-home~Home-homeTemplate~fixedDat~0938e26f.390bc523.js:1578:16)
    at __webpack_require__ (http://localhost:3000/main.f9b9cfa1.js:64:30)
    at Module../node_modules/@vaadin/vaadin-text-field/theme/lumo/vaadin-text-field.js (http://localhost:3000/vendors~BrokerOffer-brokerOffer~BrokerOffer-brokerOfferTemplate~Home-home~Home-homeTemplate~fixedDat~0938e26f.390bc523.js:1904:83)
    at __webpack_require__ (http://localhost:3000/main.f9b9cfa1.js:64:30)
    at Module../node_modules/@vaadin/vaadin-text-field/vaadin-text-field.js (http://localhost:3000/vendors~BrokerOffer-brokerOffer~BrokerOffer-brokerOfferTemplate~Home-home~Home-homeTemplate~fixedDat~0938e26f.390bc523.js:1920:90)
    at __webpack_require__ (http://localhost:3000/main.f9b9cfa1.js:64:30)
    at Module../src/views/Home/homeTemplate.js (http://localhost:3000/Home-homeTemplate.a5763f3d.js:298:104)
    at __webpack_require__ (http://localhost:3000/main.f9b9cfa1.js:64:30)
    at Module../src/views/Home/home.js (http://localhost:3000/Home-home.2e3922e6.js:12:71)
    at __webpack_require__ (http://localhost:3000/main.f9b9cfa1.js:64:30)

- [X ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

**Comment by web-padawan** [comment]
This is a known issue which will happen if you have any component depending on latest stable of `vaadin-text-field` (which is 2.5) installed in your app. 

We will release other components as alpha versions at some point, in order to be able to test how they work together. That would include RTL support among other improvements.

**Comment by web-padawan** [comment]
Closing as there is nothing that we can do except than release all the components depending on text-field as alpha versions. We will do it when we start preparing to deliver RTL support.
